# Generated by Django 3.2.8 on 2021-11-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='user_id')),
                ('text_task', models.TextField(verbose_name='text_task')),
                ('status', models.CharField(max_length=10, verbose_name='status')),
                ('topic_survey', models.CharField(max_length=50, verbose_name='topic_survey')),
            ],
        ),
    ]
