# Generated by Django 3.2.7 on 2021-11-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipr',
            name='status',
            field=models.IntegerField(verbose_name='status'),
        ),
    ]
