# Generated by Django 3.2.8 on 2021-11-04 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(verbose_name='text_answer')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_topic', models.CharField(max_length=250, verbose_name='survey_topic')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.CharField(max_length=250, verbose_name='text_question')),
                ('question_topic', models.TextField(null=True, verbose_name='question_topic')),
                ('material_link', models.TextField(null=True, verbose_name='materials_link')),
                ('id_right_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Survey.answer')),
                ('id_survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Survey.survey')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='id_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Survey.question'),
        ),
    ]
