# Generated by Django 3.2.8 on 2021-11-07 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0006_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='right_answers',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='log',
            name='wrong_answers',
        ),
        migrations.AddField(
            model_name='log',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Survey.question'),
        ),
    ]
