# Generated by Django 3.2.8 on 2021-11-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0007_auto_20211107_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='log',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='log',
            name='survey',
            field=models.TextField(blank=True, null=True, verbose_name='survey'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.TextField(blank=True, null=True, verbose_name='user'),
        ),
    ]
