# Generated by Django 3.2.8 on 2021-11-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0008_auto_20211107_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='right_answer',
            field=models.TextField(blank=True, null=True, verbose_name='right_answer'),
        ),
    ]
