# Generated by Django 3.2.7 on 2021-11-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0009_log_right_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.IntegerField(null=True, verbose_name='level'),
        ),
    ]
