# Generated by Django 3.2.7 on 2021-11-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0011_log_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text_question',
            field=models.TextField(blank=True, null=True, verbose_name='text_question'),
        ),
    ]
