# Generated by Django 3.2.8 on 2021-11-04 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='login')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('type', models.CharField(max_length=8, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=50, verbose_name='lastname')),
                ('patronymic', models.CharField(max_length=50, verbose_name='patronymic')),
                ('dateOfBirth', models.DateField(verbose_name='dateOfBirth')),
                ('gender', models.CharField(max_length=16, verbose_name='gender')),
                ('aut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Authentication.authentication')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=50, verbose_name='lastname')),
                ('patronymic', models.CharField(max_length=50, verbose_name='patronymic')),
                ('dateOfBirth', models.DateField(verbose_name='dateOfBirth')),
                ('gender', models.CharField(max_length=16, verbose_name='gender')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('aut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Authentication.authentication')),
                ('idmanager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Authentication.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=50, verbose_name='lastname')),
                ('patronymic', models.CharField(max_length=50, verbose_name='patronymic')),
                ('dateOfBirth', models.DateField(verbose_name='dateOfBirth')),
                ('gender', models.CharField(max_length=16, verbose_name='gender')),
                ('aut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Authentication.authentication')),
            ],
        ),
    ]
