# Generated by Django 3.2.8 on 2021-11-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='position',
            field=models.CharField(max_length=100, null=True, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='manager',
            name='position',
            field=models.CharField(max_length=100, null=True, verbose_name='position'),
        ),
    ]
