# Generated by Django 3.2.7 on 2021-11-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20211116_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.IntegerField(null=True, verbose_name='level'),
        ),
    ]
