# Generated by Django 3.2.7 on 2021-11-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_employee_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='link_to_photo',
            field=models.TextField(null=True, verbose_name='link_to_photo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='link_to_photo',
            field=models.TextField(null=True, verbose_name='link_to_photo'),
        ),
        migrations.AddField(
            model_name='manager',
            name='link_to_photo',
            field=models.TextField(null=True, verbose_name='link_to_photo'),
        ),
    ]
