# Generated by Django 3.2.7 on 2021-11-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_auto_20211130_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='link_to_photo',
            field=models.TextField(blank=True, null=True, verbose_name='link_to_photo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='link_to_photo',
            field=models.TextField(blank=True, null=True, verbose_name='link_to_photo'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='link_to_photo',
            field=models.TextField(blank=True, null=True, verbose_name='link_to_photo'),
        ),
    ]
